### ISSUE TITLE
Team 3045 Code Review Party

### ISSUE THREAD

**Issue by PicklesTheFrog** [FRC3636/FRC_CODE_2020#2]
Hello Team 3636,

     Our team have a less advanced software group so we may not have the best feedback. With that, here's our feedback:

     - Maybe use inline functions to compact code. On the other hand, the written out functions are very readable and your code overall is really well organized.
     - Your 2d map is really nice. 
     - Maybe add an autonomous option to shoot preloaded balls (unless I missed it in your code)

Overall, we really like your code. 
Team 3045

**Comment by LincolnSand** [comment]
>  - Maybe use inline functions to compact code. On the other hand, the written out functions are very readable and your code overall is really well organized.

inline is a linking directive. If I wanted to force function inlining, I would use the gnu annotations. In general you shouldn't force inlining of functions unless you know it will be called quite often in non-branching code.
